sudo: required
services:
    - docker
    
before_install:
    - docker build -t sandeepyadav/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true sandeepyadav/docker-react npm run test
